# docker-compose.yml

version: '3'

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: web-app
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app/apps/web # Mount the web app code for live development
    depends_on:
      - pocketbase

  pocketbase:
    build:
      context: .
      dockerfile: apps/pb/Dockerfile
    container_name: pocketbase-server
    ports:
      - "8080:8080"
    volumes:
      - ./pocketbase_data:/pb/pb_data   # Optional, to mount for live updates
